### ISSUE TITLE
Why the need for CRDs?

### ISSUE THREAD

**Issue by towolf** [Nexinto/kubernetes-icinga#2]
Salve, I was happy to find your project because I was looking for a way to dynamically create objects in Icinga to attach checks to. Your project seems to be exactly about that.

What I do not understand yet, is why the objects are **also** created in Kubernetes as CRDs. The objects to be checked are objects in Kubernetes and they should be objects in Icinga, but why do we need a third kind of object?

The controller needs to synchronize the state between Kubernetes API and Icinga API continuously anyway, so how do these CRDs help with that?

**Comment by iljaweis** [comment]
Hi there,

the idea with using CRs is that you can use them to manually add checks without having to touch Icinga instance directly (like, deploying additional checks with your application), and that you could write controllers for resource types not supported by kubernetes-icinga by just creating the CRs and having kubernetes-icinga manage all the objects in Icinga.

**Comment by towolf** [comment]
I see. From my thinking I would attach Services and other things via apply rules from the Icinga config, and I would only need the controller to dynamically create and remove objects (with the proper vars to match against).

So, your usage model is to handle the config from the Kubernetes cluster, wereas I would prefer to keep the config local to Icinga.

E.g. on Ingress object, the domain from the `host` field could be store in an Icinga var and my "apply rules" would configure an http check against that.

**Comment by iljaweis** [comment]
I'm not sure I completely understand what you described. In your first paragraph, "Service" is an Icinga Service? And you would keep rules about, say, which Icinga Service is configured for specific, say, Hosts generated by kubernetes-icinga?

You should still be able to do that. We only ever touch Icinga Objects if the var "kubernetes_cluster" is set to the correct cluster tag so that you can manually add any objects and those don't get removed.

So, using CRs should be an implementation detail that does not affect you, or am I missing something?

**Comment by towolf** [comment]
> an implementation detail that does not affect you

Im a way yes. I mostly wanted to understand what they are for.

And I had these objects still left behind after I stopped my first test, having stopped the kubernetes-icinga controller. And I needed to manually delete them. And so I wondered, "what are these for"?  

I guess my question is satisfied now.
